project_name: kube-mqtt-mirror

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:latest-amd64"
    dockerfile: Dockerfile.amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:{{ .Version }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:latest-arm64"
    dockerfile: Dockerfile.arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:{{ .Version }}
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:{{ .Version }}-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:{{ .Version }}-arm64
  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:latest
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:latest-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/kube-mqtt-mirror:latest-arm64