FROM --platform=linux/arm64 golang:1.23.4-bookworm AS builder

WORKDIR /app

# Copy binary from GoReleaser
COPY kube-mqtt-mirror /app/kube-mqtt-mirror

# Use distroless as minimal base image
FROM --platform=linux/arm64 gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /app/kube-mqtt-mirror /app/kube-mqtt-mirror

ENTRYPOINT ["/app/kube-mqtt-mirror"]
