name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-sqlite:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          CGO_ENABLED=0 go build -o kube-mqtt-mirror .
          chmod +x kube-mqtt-mirror

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          registry: true

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y iproute2

      - name: Generate TLS certificates
        run: |
          # Get Docker host IP
          DOCKER_HOST_IP=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')
          echo "Using Docker host IP: $DOCKER_HOST_IP"

          # Generate certs with Docker host IP
          openssl req -x509 -newkey rsa:2048 \
            -keyout server.key \
            -out server.crt \
            -days 365 \
            -nodes \
            -subj "/CN=localhost" \
            -addext "subjectAltName=DNS:localhost,IP:127.0.0.1,IP:$DOCKER_HOST_IP"
          chmod 600 server.key server.crt

      - name: Run Kind Test
        run: |
          # Get Docker host IP
          DOCKER_HOST_IP=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')
          echo "Using Docker host IP: $DOCKER_HOST_IP"

          # Create log file
          touch kube-mqtt-mirror.log

          # Start the program
          ./kube-mqtt-mirror \
            -webhook \
            -mirror \
            -messaging-type sqlite \
            -broker test.db \
            -webhook-port 8443 \
            -local-registry localhost:5000 \
            -insecure-registries \
            -tls-cert server.crt \
            -tls-key server.key \
            -log-file kube-mqtt-mirror.log &
          MIRROR_PID=$!

          # Show program output in real time
          tail -f kube-mqtt-mirror.log &
          TAIL_PID=$!

          # Wait for program to start
          timeout=30
          started=false
          for i in $(seq 1 $timeout); do
            if grep -q "Subscribed to topic: image/download" kube-mqtt-mirror.log; then
              echo "Program started successfully"
              started=true
              break
            fi
            echo "Waiting for program to start ($i/$timeout)..."
            sleep 1
          done

          # Stop tailing the log
          kill $TAIL_PID || true

          if [ "$started" != "true" ]; then
            echo "Program failed to start"
            cat kube-mqtt-mirror.log
            exit 1
          fi

          # Configure webhook
          CA_BUNDLE=$(cat server.crt | base64 | tr -d '\n')
          cat > webhook.yaml <<EOF
          apiVersion: admissionregistration.k8s.io/v1
          kind: MutatingWebhookConfiguration
          metadata:
            name: webhook-mirroring
          webhooks:
            - name: webhook.mirroring.example.com
              admissionReviewVersions: ["v1"]
              sideEffects: None
              rules:
                - operations: ["CREATE"]
                  apiGroups: [""]
                  apiVersions: ["v1"]
                  resources: ["pods"]
              clientConfig:
                url: "https://$DOCKER_HOST_IP:8443/webhook"
                caBundle: $CA_BUNDLE
              failurePolicy: Fail
          EOF
          
          kubectl apply -f webhook.yaml

          # Create test pod
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Pod
          metadata:
            name: webhook-test-pod
            annotations:
              webhook: "true"
          spec:
            containers:
              - name: nginx
                image: nginx
          EOF

          # Wait for image copy to complete
          echo "Waiting for image copy to complete..."
          timeout=60
          copied=false
          for i in $(seq 1 $timeout); do
            if grep -q "Image copy completed successfully" kube-mqtt-mirror.log; then
              echo "Image copy completed successfully"
              copied=true
              break
            fi
            echo "Waiting for image copy ($i/$timeout)..."
            sleep 1
          done

          if [ "$copied" != "true" ]; then
            echo "Image copy failed"
            cat kube-mqtt-mirror.log
            exit 1
          fi

          # Wait for pod to be ready
          if ! kubectl wait --for=condition=ready pod/webhook-test-pod --timeout=60s; then
            echo "Pod creation failed"
            kubectl describe pod webhook-test-pod
            kubectl logs webhook-test-pod
            exit 1
          fi

          # Verify multi-arch support
          echo "Verifying multi-arch support for nginx image..."
          MANIFEST_LIST=$(curl -s -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" http://localhost:5000/v2/nginx/manifests/latest)
          if [ $? -ne 0 ]; then
            echo "Failed to get manifest list"
            exit 1
          fi

          # Check for both amd64 and arm64 platforms
          if ! echo "$MANIFEST_LIST" | grep -q "amd64" || ! echo "$MANIFEST_LIST" | grep -q "arm64"; then
            echo "Missing architecture in manifest list:"
            echo "$MANIFEST_LIST"
            exit 1
          fi

          echo "Multi-arch verification successful - found both amd64 and arm64 architectures"

          # Cleanup
          kill $MIRROR_PID || true
          kubectl delete -f webhook.yaml
          kubectl delete pod webhook-test-pod
