name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: CGO_ENABLED=0 go build -o kube-mqtt-mirror .

      - uses: actions/upload-artifact@v3
        with:
          name: kube-mqtt-mirror
          path: kube-mqtt-mirror
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-22.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      matrix:
        messaging: [queue, mqtt, postgres]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: kube-mqtt-mirror

      - name: Make binary executable
        run: chmod +x kube-mqtt-mirror

      - name: Setup Queue Directory
        if: matrix.messaging == 'queue'
        run: mkdir -p queue

      - name: Setup MQTT
        if: matrix.messaging == 'mqtt'
        run: |
          sudo apt-get update
          sudo apt-get install -y mosquitto
          echo "listener 1883" | sudo tee /etc/mosquitto/conf.d/test.conf
          echo "allow_anonymous true" | sudo tee -a /etc/mosquitto/conf.d/test.conf
          sudo systemctl start mosquitto

      - name: Setup Postgres
        if: matrix.messaging == 'postgres'
        run: |
          # Start PostgreSQL
          docker run -d --name postgres \
            -e POSTGRES_USER=test \
            -e POSTGRES_PASSWORD=test \
            -e POSTGRES_DB=test \
            -p 5432:5432 \
            postgres:14-alpine

          # Wait for PostgreSQL to be ready
          timeout=30
          for i in $(seq 1 $timeout); do
            if docker exec postgres pg_isready -U test > /dev/null 2>&1; then
              echo "PostgreSQL is ready"
              break
            fi
            if [ $i -eq $timeout ]; then
              echo "PostgreSQL failed to start"
              exit 1
            fi
            echo "Waiting for PostgreSQL ($i/$timeout)..."
            sleep 1
          done

          # Create required table
          PGPASSWORD=test psql -h localhost -U test -d test -c "
            CREATE TABLE IF NOT EXISTS messages (
              id SERIAL PRIMARY KEY,
              topic TEXT NOT NULL,
              payload TEXT NOT NULL,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );"

      - name: Generate TLS Certificate
        run: |
          openssl req -x509 -newkey rsa:2048 \
            -keyout server.key \
            -out server.crt \
            -days 365 \
            -nodes \
            -subj "/CN=localhost" \
            -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"
          chmod 600 server.key server.crt

      - name: Start Program
        run: |
          # Configure broker based on messaging type
          case "${{ matrix.messaging }}" in
            "queue")
              BROKER_ADDR="queue/messages.json"
              ;;
            "mqtt")
              BROKER_ADDR="tcp://localhost:1883"
              ;;
            "postgres")
              BROKER_ADDR="localhost:5432"
              EXTRA_ARGS="-username test -password test"
              ;;
          esac

          ./kube-mqtt-mirror \
            -webhook \
            -mirror \
            -messaging-type ${{ matrix.messaging }} \
            -broker "$BROKER_ADDR" \
            $EXTRA_ARGS \
            -webhook-port 8443 \
            -local-registry localhost:5000 \
            -insecure-registries \
            -tls-cert server.crt \
            -tls-key server.key \
            -log-file kube-mqtt-mirror.log &
          
          timeout=30
          while ! grep -q "Subscribed to topic: image/download" kube-mqtt-mirror.log; do
            if [ $timeout -le 0 ]; then
              echo "Program failed to start"
              cat kube-mqtt-mirror.log
              exit 1
            fi
            sleep 1
            ((timeout--))
          done

      - name: Test Concurrent Pods
        run: |
          # Send multiple webhook requests concurrently
          echo "Testing concurrent pod creation..."
          for img in nginx:alpine redis:alpine postgres:alpine busybox:latest memcached:alpine; do
            curl -s -k -H "Content-Type: application/json" -d '{
              "kind": "AdmissionReview",
              "apiVersion": "admission.k8s.io/v1",
              "request": {
                "uid": "'$(uuidgen)'",
                "kind": {"group": "", "version": "v1", "kind": "Pod"},
                "resource": {"group": "", "version": "v1", "resource": "pods"},
                "operation": "CREATE",
                "object": {
                  "apiVersion": "v1",
                  "kind": "Pod",
                  "metadata": {
                    "name": "test-pod-'${img/:/-}'",
                    "annotations": {
                      "webhook": "true"
                    }
                  },
                  "spec": {
                    "containers": [
                      {
                        "name": "app",
                        "image": "'$img'"
                      }
                    ]
                  }
                }
              }
            }' https://localhost:8443/webhook &
          done

          # Wait for all images to be processed
          echo "Waiting for image processing..."
          timeout=120
          for img in nginx:alpine redis:alpine postgres:alpine busybox:latest memcached:alpine; do
            while ! grep -q "Successfully downloaded image: $img" kube-mqtt-mirror.log; do
              if [ $timeout -le 0 ]; then
                echo "Image processing failed for $img"
                cat kube-mqtt-mirror.log
                exit 1
              fi
              sleep 1
              ((timeout--))
            done
            echo "Successfully processed $img"
          done

      - name: Cleanup
        if: always()
        run: |
          # Stop program
          pkill kube-mqtt-mirror || true

          # Cleanup messaging backend
          case "${{ matrix.messaging }}" in
            "queue")
              rm -rf queue/
              ;;
            "mqtt")
              sudo systemctl stop mosquitto
              sudo rm -f /etc/mosquitto/conf.d/test.conf
              ;;
            "postgres")
              docker stop postgres
              docker rm -f postgres
              ;;
          esac

          # Cleanup common files and containers
          rm -f server.key server.crt kube-mqtt-mirror.log
          docker stop registry || true
          docker rm -f registry || true
